// Tasks
export const GET_TASKS_FAILURE = 'GET_TASKS_FAILURE';
export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS';

// Single Task
export const GET_TASK_SUCCESS = 'GET_TASK_SUCCESS';
export const GET_TASK_FAILURE = 'GET_TASK_FAILURE';
export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS';
export const ADD_TASK_FAILURE = 'ADD_TASK_FAILURE';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const DELETE_TASK_FAILURE = 'DELETE_TASK_FAILURE';
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS';
export const UPDATE_TASK_FAILURE = 'UPDATE_TASK_FAILURE';
export const MARK_TASK_COMPLETE_SUCCESS = 'MARK_TASK_COMPLETE_SUCCESS';
export const MARK_TASK_COMPLETE_FAILURE = 'MARK_TASK_COMPLETE_FAILURE';

// HABITS

export const GET_HABITS_SUCCESS = 'GET_HABITS_SUCCESS';
export const GET_HABITS_FAILURE = 'GET_HABITS_FAILURE';
export const GET_HABIT_SUCCESS = 'GET_HABIT_SUCCESS';
export const GET_HABIT_FAILURE = 'GET_HABIT_FAILURE';
export const DELETE_HABIT_SUCCESS = 'DELETE_HABIT_SUCCESS';
export const DELETE_HABIT_FAILURE = 'DELETE_HABIT_FAILURE';

// TODAY

export const GET_TODAY_SUCCESS = 'GET_TODAY_SUCCESS';
export const GET_TODAY_FAILURE = 'GET_TODAY_FAILURE';
export const ASSIGN_TASK_TO_DAY_SUCCESS = 'ASSIGN_TASK_TO_DAY_SUCCESS';
export const ASSIGN_TASK_TO_DAY_FAILURE = 'ASSIGN_TASK_TO_DAY_FAILURE';
