// Tasks
export const GET_TASKS_FAILURE = 'GET_TASKS_FAILURE';
export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS';

// Single Task
export const GET_TASK_SUCCESS = 'GET_TASK_SUCCESS';
export const GET_TASK_FAILURE = 'GET_TASK_FAILURE';
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS';
export const UPDATE_TASK_FAILURE = 'UPDATE_TASK_FAILURE';
export const MARK_TASK_COMPLETE_SUCCESS = 'MARK_TASK_COMPLETE_SUCCESS';
export const MARK_TASK_COMPLETE_FAILURE = 'MARK_TASK_COMPLETE_FAILURE';
